app/core/models.py
# Copyright 2014 SolidBuilds.com. All rights reserved
#
# Authors: Ling Thio <ling.thio@gmail.com>

from flask_user import UserMixin
from flask_user.forms import RegisterForm
from flask_wtf import Form
from wtforms import StringField, SubmitField, validators
from app import db


# Define the User data model. Make sure to add the flask_user.UserMixin !!
class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)

    # User authentication information (required for Flask-User)
    email = db.Column(db.Unicode(255), nullable=False, server_default=u'', unique=True)
    confirmed_at = db.Column(db.DateTime())
    password = db.Column(db.String(255), nullable=False, server_default='')
    reset_password_token = db.Column(db.String(100), nullable=False, server_default='')
    active = db.Column(db.Boolean(), nullable=False, server_default='0')

    # User information
    active = db.Column('is_active', db.Boolean(), nullable=False, server_default='0')
    first_name = db.Column(db.Unicode(50), nullable=False, server_default=u'')
    last_name = db.Column(db.Unicode(50), nullable=False, server_default=u'')

    # Relationships
    roles = db.relationship('Role', secondary='users_roles',
                            backref=db.backref('users', lazy='dynamic'))


# Define the Role data model
class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, server_default=u'', unique=True)  # for @roles_accepted()
    label = db.Column(db.Unicode(255), server_default=u'')  # for display purposes

# Define the Microapp data model
class Microapp(db.Model):
    __tablename__ = 'microapps'
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(50), nullable=False, server_default=u'', unique=True)  # for @roles_accepted()
    label = db.Column(db.Unicode(255), server_default=u'')  # for display purposes
    is_active = db.Column(db.Boolean(), nullable=False, server_default=u'0')


# Define the UserRoles association model
class UsersRoles(db.Model):
    __tablename__ = 'users_roles'
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey('users.id', ondelete='CASCADE'))
    role_id = db.Column(db.Integer(), db.ForeignKey('roles.id', ondelete='CASCADE'))


# Define the User registration form
# It augments the Flask-User RegisterForm with additional fields
class MyRegisterForm(RegisterForm):
    first_name = StringField('First name', validators=[
        validators.DataRequired('First name is required')])
    last_name = StringField('Last name', validators=[
        validators.DataRequired('Last name is required')])


# Define the User profile form
class UserProfileForm(Form):
    first_name = StringField('First name', validators=[
        validators.DataRequired('First name is required')])
    last_name = StringField('Last name', validators=[
        validators.DataRequired('Last name is required')])
    submit = SubmitField('Save')

app/__init__.py
# __init__.py is a special Python file that allows a directory to become
# a Python package so it can be accessed using the 'import' statement.

from flask import Flask
from flask_script import Manager
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)           # The WSGI compliant web application object
db = SQLAlchemy(app)            # Setup Flask-SQLAlchemy
manager = Manager(app)          # Setup Flask-Script

from app.startup.create_app import create_app

app/core/__init__.py
# __init__.py is a special Python file that allows a directory to become
# a Python package so it can be accessed using the 'import' statement.

from . import manager
from . import models
from . import views

app/core/views.py
# Copyright 2014 SolidBuilds.com. All rights reserved
#
# Authors: Ling Thio <ling.thio@gmail.com>


from flask import redirect, render_template, render_template_string, Blueprint
from flask import request, url_for
from flask_user import current_user, login_required, roles_accepted
from app import app, db
from models import Microapp
from app.core.models import UserProfileForm

core_blueprint = Blueprint('core', __name__, url_prefix='/')


# The Home page is accessible to anyone
@core_blueprint.route('')
def home_page():
    return render_template('core/home_page.html')


# The User page is accessible to authenticated users (users that have logged in)
@core_blueprint.route('dashboard')
@login_required  # Limits access to authenticated users
def dashboard():
    return render_template('core/dashboard.html')

# The User page is accessible to authenticated users (users that have logged in)
@core_blueprint.route('appstore')
@login_required  # Limits access to authenticated users
def appstore():
    active_microapps = db.session.query(Microapp).filter_by(is_active=True).all()
    return render_template('core/appstore.html', active_microapps=active_microapps)

# The Admin page is accessible to users with the 'admin' role
@core_blueprint.route('admin')
@roles_accepted('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('core/admin_page.html')


@core_blueprint.route('user/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():
    # Initialize form
    form = UserProfileForm(request.form, current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():
        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('core.home_page'))

    # Process GET or invalid POST
    return render_template('core/user_profile_page.html',
                           form=form)


# Register blueprint
app.register_blueprint(core_blueprint)

app/startup/__init__.py
# __init__.py is a special Python file that allows a directory to become
# a Python package so it can be accessed using the 'import' statement.

# Intentionally left empty

app/templates/common/form_macros.html
{% macro render_field(field, label=None, label_visible=true, right_url=None, right_label=None) -%}
    <div class="form-group {% if field.errors %}has-error{% endif %} {{ kwargs.pop('class_', '') }}">
        {% if field.type != 'HiddenField' and label_visible %}
            {% if not label %}{% set label=field.label.text %}{% endif %}
            <label for="{{ field.id }}" class="control-label">{{ label|safe }}</label>
        {% endif %}
        {{ field(class_='form-control', **kwargs) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>
{%- endmacro %}
 
{% macro render_checkbox_field(field, label=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ label }}
        </label>
    </div>
{%- endmacro %}
 
{% macro render_radio_field(field) -%}
    {% for value, label, checked in field.iter_choices() %}
        <div class="radio">
            <label>
                <input type="radio" name="{{ field.id }}" id="{{ field.id }}" value="{{ value }}"{% if checked %} checked{% endif %}>
                {{ label }}
            </label>
        </div>
    {% endfor %}
{%- endmacro %}

{% macro render_submit_field(field, label=None, tabindex=None) -%}
    {% if not label %}{% set label=field.label.text %}{% endif %}
    {#<button type="submit" class="form-control btn btn-default btn-primary">{{label}}</button>#}
    <input type="submit" value="{{label}}"
           {% if tabindex %}tabindex="{{ tabindex }}"{% endif %}
           >
{%- endmacro %}

app/templates/common/page_base.html
{% extends "layout.html" %}

app/templates/core/admin_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>Admin page</h1>

<p>This page is accessible to authenticated users with the 'admin' role.</p>

{% endblock %}

app/templates/core/appstore.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>Appstore page</h1>

<p>This page is accessible to authenticated user (users that have signed in).</p>

<div class="list-group">
{% for microapp in active_microapps %}
    <a href="microapp/{{ microapp.name }}" class="list-group-item">{{ microapp.name }}</a>
{% endfor %}
</div>

{% endblock %}

app/templates/core/dashboard.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>Dashboard page</h1>

<p>This page is accessible to authenticated user (users that have signed in).</p>

{% endblock %}

app/templates/core/home_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>Home page</h1>

<p>This page is accessible to any user (signed in or not)</p>

{% if not current_user.is_authenticated %}
<p>
To view the User page, you must
<a href="{{ url_for('user.login') }}">Sign in</a> or
<a href="{{ url_for('user.register') }}">Register</a>.
</p>
{% endif %}

<p>
    Test users:<br/>
    - user@example.com / Password1<br/>
    - admin@example.com / Password1
</p>

{% endblock %}

app/templates/core/user_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>User page</h1>

<p>This page is accessible to authenticated user (users that have signed in).</p>

{% endblock %}

app/templates/core/user_profile_page.html
{% extends "common/page_base.html" %}  {# common/page_base.html extends layout.html #}

{% block content %}
<h1>User Profile</h1>

<p><a href="{{ url_for('user.change_password') }}">Change password</a></p>

{% from "common/form_macros.html" import render_field, render_submit_field %}
<form action="" method="POST" class="form" role="form">
  <div class="row">
    <div class="col-sm-6 col-md-5 col-lg-4">
    {{ form.hidden_tag() }}

    {{ render_field(form.first_name, tabindex=240) }}

    {{ render_field(form.last_name, tabindex=250) }}

    {{ render_submit_field(form.submit, tabindex=280) }}
    </div>
  </div>
</form>

{% endblock %}

app/templates/flask_user/flask_user_base.html
{% extends "layout.html" %}


{% block pre_content %}
<div class="container">
    <div class="row">
        <div class="col-sm-7 col-md-6 col-lg-5 col-centered">
{% endblock %}


{% block post_content %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/flask_user/member_base.html
{% extends 'flask_user/flask_user_base.html' %}

app/templates/flask_user/public_base.html
{% extends 'flask_user/flask_user_base.html' %}

app/templates/flask_user/register.html
{% extends 'flask_user/public_base.html' %}

{% block content %}
{% from "flask_user/_macros.html" import render_field, render_submit_field %}
<h1>{%trans%}Register{%endtrans%}</h1>

<form action="" method="POST" novalidate formnovalidate class="form" role="form">
    {{ form.hidden_tag() }}

    {# Username or Email #}
    {% set field = form.username if user_manager.enable_username else form.email %}
    <div class="form-group {% if field.errors %}has-error{% endif %}">
        {# Label on left, "Already registered? Sign in." on right #}
        <div class="row">
            <div class="col-xs-6">
                <label for="{{ field.id }}" class="control-label">{{ field.label.text }}</label>
            </div>
            <div class="col-xs-6 text-right">
                {% if user_manager.enable_register %}
                    <a href="{{ url_for('user.login') }}" tabindex='290'>
                        {%trans%}Already registered? Sign in.{%endtrans%}</a>
                {% endif %}
            </div>
        </div>
        {{ field(class_='form-control', tabindex=210) }}
        {% if field.errors %}
            {% for e in field.errors %}
                <p class="help-block">{{ e }}</p>
            {% endfor %}
        {% endif %}
    </div>

    {% if user_manager.enable_email and user_manager.enable_username %}
        {{ render_field(form.email, tabindex=220) }}
    {% endif %}

    {{ render_field(form.first_name, tabindex=240) }}

    {{ render_field(form.last_name, tabindex=250) }}

    {{ render_field(form.password, tabindex=260) }}

    {% if user_manager.enable_retype_password %}
        {{ render_field(form.retype_password, tabindex=270) }}
    {% endif %}

    {{ render_submit_field(form.submit, tabindex=280) }}
</form>

{% endblock %}

app/templates/layout.html
<!doctype html>
<html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Clusterfvck - Your dashboard of cool apps</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Optional apple-touch-icon
        <link rel="apple-touch-icon" href="apple-touch-icon.png"> -->
        <!-- Place favicon.ico in the root directory -->

        <!-- HTML5 boilerplate CSS -->
        <link rel="stylesheet" href="/static/html5boilerplate/css/normalize.css">
        <link rel="stylesheet" href="/static/html5boilerplate/css/main.css">
        <script src="/static/html5boilerplate/js/modernizr-2.8.3.min.js"></script>

        <!-- Application specific CSS-->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/app/app.css">
    </head>
    <body>
        {% block body %}
        <!-- Application specific HTML -->
        <div id="header-div" class="clearfix with-margins">
            <div class="pull-left"><a href="{{ url_for('core.home_page') }}"><span class="header-title">Clusterfvck</span></a></div>
            <div class="pull-right">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('core.user_profile_page') }}">{{ current_user.first_name or current_user.user_auth.username }}</a>
                    &nbsp; | &nbsp;
                    <a href="{{ url_for('user.logout') }}">Sign out</a>
                {% else %}
                    <a href="{{ url_for('user.login') }}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <div class="with-margins">
            <a href="{{ url_for('core.home_page') }}">Home</a>
            &nbsp; | &nbsp; <a href="{{ url_for('core.dashboard') }}">Your Dashboard</a>
            &nbsp; | &nbsp; <a href="{{ url_for('core.appstore') }}">App Store</a>
        </div>
        <hr class="no-margins"/>

        <div id="main-div" class="with-margins">
        {% block pre_content %}{% endblock %}

        {# One-time system messages called Flash messages #}
        {% block flash_messages %}
            {%- with messages = get_flashed_messages(with_categories=true) -%}
                {% if messages %}
                    {% for category, message in messages %}
                        {% if category=='error' %}
                            {% set category='danger' %}
                        {% endif %}
                        <div class="alert alert-{{category}}">{{ message|safe }}</div>
                    {% endfor %}
                {% endif %}
            {%- endwith %}
        {% endblock %}

        {% block content %}{% endblock %}

        {% block post_content %}{% endblock %}
        </div>

        <br/>
        <hr class="no-margins"/>
        <div id="footer-div" class="clearfix with-margins">
            <div class="pull-left">Dashboard v1.0</div>
            <div class="pull-right">Dashboard</div>
        </div>

        <!-- Application specific JS -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <!-- HTML5 boilerplate JS -->
        <script src="/static/html5boilerplate/js/main.js"></script>

        <!-- Optional Google Analytics: change UA-XXXXX-X to be your site's ID.
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        -->
        {% endblock %}
    </body>
</html>